### ISSUE TITLE
API 28.

### ISSUE THREAD

**Issue by textbrowser** [textbrowser/smokestack#2]
API 28 port.

**Comment by textbrowser** [comment]
Completed and included with 2023.12.25.

**Comment by licaon-kter** [comment]
Any reason to bump `minSdk` so **only** Android 9 or later can install it?

**Comment by textbrowser** [comment]
It was recommended by Android Studio. What was it before? 25?

**Comment by licaon-kter** [comment]
This year you went from 19 to 25 and now to 28

> recommended by Android Studio

Afaik, Google enforces bumps of `targetSdk`, not of `minSdk`, so was that something that needed to be done, eg. Some lib or dep needs minSdk 25/28 or was this bumped out of error to match targetSdk.

minSdk and targetSdk are very different things :)

**Comment by textbrowser** [comment]
I test with Android 10 and 13.  Smoke is a lovely hobby and I have zero insight into its use. People have not raised objections into my haphazard API decisions. :) Smoke used to have a free public server. Now that it doesn't, people do not complain nor offer their own free public servers. So, we're free to decide the future. APIs 31 and 32 are good too. 34 is also present. It's nice to want to support ancient devices. Why? If zero people are interested, I cannot remain whimsical because there is a 0.0001 probability that someone will find Smoke interesting. Anyway, remaining current is important because it's very difficult to upgrade Android software. At least for me. Enough things become broken and/or deprecated.

**Comment by textbrowser** [comment]
Java doesn't have beautiful conditional compilation. Android offers odd versioning gimmicks and it later complains about these choices if you dare inspect your source through its algorithms. So you can put a lot of effort into various Android versions only to be insulted for your cleverness. Android is nice and nicely fragmented.

**Comment by textbrowser** [comment]
I prefer Qt and it works well on Android. It's different but the differences don't tire me. Know what I mean?

**Comment by textbrowser** [comment]
Except for the cryptography thing. Qt doesn't have native libraries for encryption.

**Comment by textbrowser** [comment]
So you have to use OpenSSL which is available. :)

**Comment by textbrowser** [comment]
Google has requirements for new programs.

https://developer.android.com/google/play/requirements/target-sdk

**Comment by licaon-kter** [comment]
> https://developer.android.com/google/play/requirements/target-sdk

Yes, like I said `targetSdk` not `min` :) 

> I prefer Qt and it works well on Android

Too bad its built libs are not FOSS and one needs to rebuild them from scratch

> So, we're free to decide the future.

Of course, as you see fit :)

**Comment by textbrowser** [comment]
This and Smoke min. @ 25 now.

**Comment by textbrowser** [comment]
I'll find a new icon for Stack and release it with the new minimum.

**Comment by licaon-kter** [comment]
One interesting side effect is that the APKs are now half size, is this as expected?

**Comment by textbrowser** [comment]
Maybe.

https://issuetracker.google.com/issues/127691661?pli=1

**Comment by licaon-kter** [comment]
M+ means 23+ so current 25 and previous 28 should behave the same

yeah, whatever :)

**Comment by textbrowser** [comment]
Google doesn't understand their products.
