### ISSUE TITLE
Android 12+13: algorithm provider link - SHA512WITHRSA for provider BC

### ISSUE THREAD

**Issue by Sammysupport** [textbrowser/smokestack#3]
Hello, 

just discovered this server at f-droid.org and installed it on Android 9, 12+13.
12+13 provide: An error (cannot create signer: no such algorithm: SHA512WITHRSA for provider BC) occured..

cf. 
https://stackoverflow.com/questions/8778531/bouncycastle-does-not-find-algorithms-that-it-provides
https://juejin.cn/post/7133095304391295007

probably for Android 12+13 the security provicer BC must be added to java:

You can add Bouncy Castle to security providers on Your java platform in two steps:

1. Copy BC librarys (currently bcpkix-jdk15on-149.jar, bcprov-jdk15on-149.jar) to directory $JAVA_HOME/jre/lib/ext/

2. Register BC provider: edit file $JAVA_HOME/jre/lib/security/java.security and under line

security.provider.1=sun.security.provider.Sun
add Your BC provider

security.provider.2=org.bouncycastle.jce.provider.BouncyCastleProvider

Change numbers of rest providers. The whole block of providers should be similar to:

security.provider.1=sun.security.provider.Sun
security.provider.2=org.bouncycastle.jce.provider.BouncyCastleProvider
...

probably an android-issue to consider for a new update, otherwise clients cannot connect. 
Sammy

**Comment by textbrowser** [comment]
There is a reminder for upgrading to a newer API. The SHA512WithRSA is not provided by Bouncy Castle. It's native to Android.

https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html

**Comment by textbrowser** [comment]
I see. Stack utilizes the BC implementation. You're correct. They removed it.

**Comment by textbrowser** [comment]
Yeah and we don't want an override. We want a replacement. I see the error.

**Comment by textbrowser** [comment]
The page in the error: https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html.

**Comment by textbrowser** [comment]
Completed! 2023.12.25.
